services:
  - type: web
    name: moyenne-isetcom-master
    env: node
    buildCommand: "npm install"
    startCommand: "npm start"
    plan: free
    region: oregon
    branch: main
    healthCheckPath: "/"
    autoDeploy: true
    envVars:
      - key: MONGODB_URI
        value: "mongodb+srv://amaramehdi3:Legocity2020@cluster0.2m66m.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
      - key: JWT_SECRET
        value: "your_jwt_secret"
sourceDir: .
nodeVersion: "18"
envVars:
  NODE_ENV: production
