services:
  - type: web
    name: moyensy-backend
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
sourceDir: .
nodeVersion: "18"
envVars:
  MONGODB_URI: mongodb+srv://Amaramehdi2:Legocity20@cluster0.2m66m.mongodb.net/moyenne-isetcom?retryWrites=true&w=majority
  JWT_SECRET: UnNouveauSecretTresSecurise2024
  NODE_ENV: production
